### ISSUE TITLE
Control plane only supports hard-coded system namespaces

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#197]
The fedv2 control plane currently sources `FederatedCluster` resources and their associated secrets from the `federation-system` namespace and `Cluster` resources from the `kube-multicluster-public` namespace.  It would be preferable to allow the names of these namespaces to vary to allow for test isolation on shared clusters and give operators flexibility in how they deploy federation.

Tasks:
- [x] Allow the federation namespace to be configured in testing (#198)
- [x] Update FederatedTypeConfig to be namespace-scoped (#209)
- [x] Update FederatedNamespacePlacement to be namespace-scoped (#210)
- [x] Allow the cluster registry namespace to vary in testing (#211)
- [x] Enable the federation control plane to target a single namespace (#212)
- [x] Enable kubefed2 configuration of federation and cluster namespaces (#213)
- [x] Enable kubefed2 joining of a cluster for only a single namespace (#215)
- [x] Support deploying namespaced control plane (#216)
- [x] Ensure control plane can run with only authz for the namespace it runs in (#230)
- [x] Update docs to reflect option to deploy control plane namespaced (#264)

**Comment by marun** [comment]
Initial implementation complete!
