### ISSUE TITLE
API driven federation of arbitrary types

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/federation-v2#60]
Related to #34; assuming that we have a CRD-based way to extend federation by creating some new CRD resources for:

- template
- override
- placement

...then there should be an API resource to have these CRDs created automatically. Example:

```yaml
kind: FederatedAPI
metadata:
  name: statefulset
spec:
  basis:
    group: apps
    version: v1
    kind: StatefulSet
  target:
    group: federation.k8s.io
    version: v1alpha1
```

A controller would list/watch this API resource and ensure that the correct CRDs were created for the named `basis` in the API group/version described by `target. In this example those would be:

- `FederatedStatefulSet` (possibly creating the OpenAPI schema and validations based on the OpenAPI for the basis type)
- `FederatedStatefulSetOverride`
- `FederatedStatefulSetPlacement`

In order to have automatic federation of all the registered types in an API server, there could also be a controller that examines the discovery endpoint for a cluster and ensures a `FederatedAPI` exists for the right API services. There are a number of ways a controller might be configured, like:

- configmap holding explicit configuration
- annotations on `APIService` and `CustomResourceDefinition` resources

idea formulated with @marun 

**Work Items**

- [x] Factor propagated version handling out of the sync controller (#273)
- [x] Factor type-specific version manager code into adapter (#276)
- [x] Add api generation to kubefed (??)

**Comment by danehans** [comment]
@pmore do you know what remains to close this issue?

**Comment by pmorie** [comment]
@danehans the remaining bit is actually generating the federation APIs themselves. For example, imagine if creating a FederatedTypeConfig actually caused the federation APIs to be generated.

**Comment by pmorie** [comment]
Maybe we should split that piece into a separate issue.

**Comment by danehans** [comment]
@pmorie OK. Is anyone working on this remaining bit?

**Comment by danehans** [comment]
@pmorie I created [this diagram](https://docs.google.com/drawings/d/1Glq-pI79ZYbb7h4GBqWwTUFavMilwg_ch_LWkThOIrM/edit?usp=sharing) to illustrate what you described [above](https://github.com/kubernetes-sigs/federation-v2/issues/60#issue-317369700). Let me know if I captured it correctly.

**Comment by marun** [comment]
@danehans I'm working on this.

**Comment by marun** [comment]
@pmorie With the switch to generation of federated types via the `kubefed2` cli command, I think this issue should be closed.  If/when it becomes desirable to support this behavior via an api, that can be filed as a new issue that takes into account the current state-of-the-art.
