### ISSUE TITLE
Enable race detection in CI

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#623]
The recent changes to replace the generated clients introduced CI instability.  Anders Janmyr was first to notice this, and thought to enable the race detector (`-race').  Races were detected in the following code:

 - [x] Generic client construction (new race, fixed by #620)
 - [x] Version manager (new race, fixed by #624)
 - [x] Passing a shared config to generic client construction (new, fixed by #624)
 - [x] Scheduling (old, fixed by #626)
 - [x] Enable race detection in managed test run (since controllers are run in-process) (fixed by #626)

To prevent the introduction of new races, race detection needs to be turned on in CI for the managed fixture (which runs the controllers in-process).  CI won't pass until the above races are fixed, though.
